export const fonts = [
    { name: 'Roboto', family: 'Roboto' },
    { name: 'Noto Sans JP', family: 'Noto Sans JP' },
    { name: 'Montserrat', family: 'Montserrat' },
    { name: 'Lato', family: 'Lato' },
    { name: 'Poppins', family: 'Poppins' },
    { name: 'Roboto Condensed', family: 'Roboto Condensed' },
    { name: 'Inter', family: 'Inter' },
    { name: 'Material Icons', family: 'Material Icons' },
    { name: 'Oswald', family: 'Oswald' },
    { name: 'Roboto Mono', family: 'Roboto Mono' },
    { name: 'Noto Sans', family: 'Noto Sans' },
    { name: 'Raleway', family: 'Raleway' },
    { name: 'Playfair Display', family: 'Playfair Display' },
    { name: 'Nunito Sans', family: 'Nunito Sans' },
    { name: 'Ubuntu', family: 'Ubuntu' },
    { name: 'Noto Sans KR', family: 'Noto Sans KR' },
    { name: 'Rubik', family: 'Rubik' },
    { name: 'Merriweather', family: 'Merriweather' },
    { name: 'Nunito', family: 'Nunito' },
    { name: 'Roboto Slab', family: 'Roboto Slab' },
    { name: 'Noto Sans TC', family: 'Noto Sans TC' },
    { name: 'PT Sans', family: 'PT Sans' },
    { name: 'Kanit', family: 'Kanit' },
    { name: 'Lora', family: 'Lora' },
    { name: 'Work Sans', family: 'Work Sans' },
    { name: 'Fira Sans', family: 'Fira Sans' },
    { name: 'DM Sans', family: 'DM Sans' },
    { name: 'Mulish', family: 'Mulish' },
    { name: 'Barlow', family: 'Barlow' },
    { name: 'Quicksand', family: 'Quicksand' },
    { name: 'PT Serif', family: 'PT Serif' },
    { name: 'Heebo', family: 'Heebo' },
    { name: 'Manrope', family: 'Manrope' },
    { name: 'IBM Plex Sans', family: 'IBM Plex Sans' },
    { name: 'Noto Serif', family: 'Noto Serif' },
    { name: 'Libre Franklin', family: 'Libre Franklin' },
    { name: 'Titillium Web', family: 'Titillium Web' },
    { name: 'Noto Sans SC', family: 'Noto Sans SC' },
    { name: 'Karla', family: 'Karla' },
    { name: 'Josefin Sans', family: 'Josefin Sans' },
    { name: 'Mukta', family: 'Mukta' },
    { name: 'Inconsolata', family: 'Inconsolata' },
    { name: 'Nanum Gothic', family: 'Nanum Gothic' },
    { name: 'Arimo', family: 'Arimo' },
    { name: 'Libre Baskerville', family: 'Libre Baskerville' },
    { name: 'Dosis', family: 'Dosis' },
    { name: 'Material Icons Outlined', family: 'Material Icons Outlined' },
    { name: 'PT Sans Narrow', family: 'PT Sans Narrow' },
    { name: 'Noto Sans HK', family: 'Noto Sans HK' }
];